name: violence_detect
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - opencv=4.6.0
  - flask=2.2.3
  - werkzeug=2.2.3
  - pillow=9.4.0
  - matplotlib=3.7.1
  - pip
  - pip:
      - tensorflow==2.10.0
      - tqdm==4.65.0
      - albumentations==1.3.0
      - seaborn==0.12.2
